#!/usr/bin/env bash
# Script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process
# Cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep bash
